Improve reference wallet
spruceid/mobile-sdk-kt pull request #26
Opened 2024-09-04 18:52 UTC by Juliano1612

This improves the reference wallet adding a better UI and more features.

2024-09-05 15:45 UTC, w4ll3 requested changes

2024-09-05 15:45 UTC, w4ll3 commented on example/src/main/java/com/spruceid/mobilesdkexample/ui/theme/Type.kt
>          /* Other default text styles to override
Remove this comment

2024-09-05 15:50 UTC, w4ll3 approved these changes

2024-09-06 10:38 UTC, sbihel approved these changes

2024-09-06 12:12 UTC, merged